// The recorded footage that stands in for the camera in demo mode
// (COMPONENTS.md §5.1: "드론이 현장에서 촬영" -> res/static 의 촬영 영상 리소스).
//
// CODEC — read this before trusting a VideoSegment
// ------------------------------------------------
// The clips were flown and recorded as H.264 High 10 (res/static/video/*.mp4).
// The wire contract admits only `codec: 'h265'`, because a real 5G drone uplink
// is H.265. Rather than label an H.264 file as h265, the footage is really
// transcoded once into res/static/video/h265/ (HEVC Main 10, ~12 Mbps, 2 s GOP)
// by tools/transcodeDemoFootage.ts, and it is those files a demo VideoSegment
// points at. So `codec: 'h265'` on the wire is TRUE.
//
// What is still simulated: the encode happened ahead of time, not live from a
// sensor, and one whole clip stands in for one route slice regardless of how
// long that slice actually took. See capture.ts for the path that encodes live.
//
// Every number below was measured with ffprobe on the generated files, so a
// VideoSegment carries real byte counts and real durations.

export type ClipPosition = 'left' | 'center' | 'right';
export type FlightDirection = 'forward' | 'backward';

/** Codec of a file on disk. Wider than the wire type on purpose: this describes
 *  what IS there, which is the only way to notice a mismatch. */
export type ClipCodec = 'h265' | 'h264';

export interface DemoClip {
  file: string;
  uri: string;
  position: ClipPosition;
  /** Direction the clip was flown in; the centre pass has no backward take. */
  direction: FlightDirection;
  /** Measured, not assumed. */
  codec: ClipCodec;
  bytes: number;
  durationMs: number;
  width: number;
  height: number;
  fps: number;
}

/** Source footage as recorded (H.264). Kept for provenance and re-encoding. */
export const DEMO_SOURCE_DIR = '/res/static/video';
/** What the drone actually ships — generated by tools/transcodeDemoFootage.ts. */
export const DEMO_FOOTAGE_DIR = '/res/static/video/h265';

const BASE = DEMO_FOOTAGE_DIR;

export const DEMO_CLIPS: DemoClip[] = [
  { file: 'demo_left.mp4',           uri: `${BASE}/demo_left.mp4`,           position: 'left',   direction: 'forward',  codec: 'h265', bytes: 17_212_642, durationMs: 11_294, width: 3840, height: 2160, fps: 59.94 },
  { file: 'demo_center.mp4',         uri: `${BASE}/demo_center.mp4`,         position: 'center', direction: 'forward',  codec: 'h265', bytes: 20_405_396, durationMs: 13_113, width: 3840, height: 2160, fps: 59.94 },
  { file: 'demo_right.mp4',          uri: `${BASE}/demo_right.mp4`,          position: 'right',  direction: 'forward',  codec: 'h265', bytes: 18_728_316, durationMs: 12_129, width: 3840, height: 2160, fps: 59.94 },
  { file: 'demo_right_backward.mp4', uri: `${BASE}/demo_right_backward.mp4`, position: 'right',  direction: 'backward', codec: 'h265', bytes: 18_315_606, durationMs: 11_928, width: 3840, height: 2160, fps: 59.94 },
  { file: 'demo_left_backward.mp4',  uri: `${BASE}/demo_left_backward.mp4`,  position: 'left',   direction: 'backward', codec: 'h265', bytes: 17_538_093, durationMs: 11_678, width: 3840, height: 2160, fps: 59.94 },
];

/** Split the route into thirds and name each third by where it sits. */
export function positionForFraction(fraction: number): ClipPosition {
  if (fraction < 1 / 3) return 'left';
  if (fraction < 2 / 3) return 'center';
  return 'right';
}

/**
 * Pick the clip that matches where along the route the slice was flown and
 * which way the drone was pointing. There is no backward take of the centre
 * pass, so the forward one is reused for it.
 */
export function pickClip(fraction: number, direction: FlightDirection): DemoClip {
  const position = positionForFraction(fraction);
  const exact = DEMO_CLIPS.find((c) => c.position === position && c.direction === direction);
  if (exact) return exact;
  const byPosition = DEMO_CLIPS.find((c) => c.position === position);
  return byPosition ?? DEMO_CLIPS[0];
}

/**
 * Narrow a clip's measured codec to what the wire allows.
 *
 * This is the guard that keeps the contract honest: if someone points the demo
 * at the un-transcoded H.264 originals, this throws instead of stamping `h265`
 * on an H.264 file. The fix is to run tools/transcodeDemoFootage.ts, not to
 * relax this check.
 */
export function wireCodecOf(clip: DemoClip): 'h265' {
  if (clip.codec !== 'h265') {
    throw new Error(
      `demo clip ${clip.file} is ${clip.codec}, but VideoSegment.codec admits only 'h265'. ` +
        'Run: npx tsx src/skylens_drone/tools/transcodeDemoFootage.ts',
    );
  }
  return clip.codec;
}
